### ISSUE TITLE
Issue while deploying SAM-TRE stack

### ISSUE THREAD

**Issue by KMPhaniKumar** [aws-samples/service-catalog-engine-for-terraform-os#34] opened 2023-04-25 10:16 UTC
While deploying SAM-TRE stack it is failing due to s3 bucket issue, it is throwing the error like below
Bucket cannot have
                                      ACLs set with
                                      ObjectOwnership's
                                      BucketOwnerEnforced
                                      setting (Service:
                                      Amazon S3; Status
                                      Code: 400; Error Code:
                                      InvalidBucketAclWithOb
                                      jectOwnership; 
                                      null)

if i comment out the line 409 from template.yaml i can able to deploy it.

**Comment by zipengw27** [comment] 2023-04-25 18:50
Hi @KMPhaniKumar ,

Thank you for reaching out.

This issue appears to be a duplicate of #24 . We have merged a [PR](https://github.com/aws-samples/service-catalog-engine-for-terraform-os/pull/32) to fix this. Please pull the latest changes and try again.

Thank you.

**Closed by zipengw27** 2023-04-25 18:50 UTC
